[package]
name = "rust_http_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
reqwest = "0.11"
futures = "0.3.19"
error-chain = "0.12.4"